### ISSUE TITLE
[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:

### ISSUE THREAD

**Issue by NTMS2017** [anilcancakir/flutter-internationalization#1]
Hi,

Try to run your app and I get this error: Any idea, what went missing?

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Skipping compilation. Fingerprint match.
Built build/app/outputs/apk/debug/app-debug.apk (30.7MB).
I/FlutterActivityDelegate(16145): onResume setting current activity to this
E/flutter (16145): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (16145): type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>' where
E/flutter (16145):   _InternalLinkedHashMap is from dart:collection
E/flutter (16145):   String is from dart:core
E/flutter (16145):   Map is from dart:core
E/flutter (16145):   String is from dart:core
E/flutter (16145):   String is from dart:core
E/flutter (16145): 
E/flutter (16145): #0      DemoLocalizations.load (file:///Users/niyazitoros/Downloads/flutter-internationalization-master/lib/main.dart:21:28)
E/flutter (16145): <asynchronous suspension>
E/flutter (16145): #1      DemoLocalizationsDelegate.load (file:///Users/niyazitoros/Downloads/flutter-internationalization-master/lib/main.dart:39:25)
E/flutter (16145): <asynchronous suspension>
E/flutter (16145): #2      _loadAll (package:flutter/src/widgets/localizations.dart:57:49)
E/flutter (16145): #3      _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:504:62)
E/flutter (16145): #4      _LocalizationsState.initState (package:flutter/src/widgets/localizations.dart:469:5)
E/flutter (16145): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3743:58)
E/flutter (16145): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
E/flutter (16145): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
E/flutter (16145): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
E/flutter (16145): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
E/flutter (16145): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
E/flutter (16145): #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
E/flutter (16145): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
E/flutter (16145): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
E/flutter (16145): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
E/flutter (16145): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
E/flutter (16145): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
E/flutter (16145): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
E/flutter (16145): #18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
E/flutter (16145): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
E/flutter (16145): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
E/flutter (16145): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
E/flutter (16145): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
E/flutter (16145): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
E/flutter (16145): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
E/flutter (16145): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
E/flutter (16145): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
E/flutter (16145): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
E/flutter (16145): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
E/flutter (16145): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
E/flutter (16145): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
E/flutter (16145): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
E/flutter (16145): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
E/flutter (16145): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
E/flutter (16145): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
E/flutter (16145): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
E/flutter (16145): #36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
E/flutter (16145): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
E/flutter (16145): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
E/flutter (16145): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
E/flutter (16145): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
E/flutter (16145): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
E/flutter (16145): #42     ComponentElement._firstBuild (package:flu
D/        (16145): HostConnection::get() New Host Connection established 0x9a39eec0, tid 16164
D/EGL_emulation(16145): eglMakeCurrent: 0x9b635ea0: ver 3 0 (tinfo 0x8a320b80)
Syncing files to device Android SDK built for x86...

**Comment by mdudek** [comment]
Just change:
Map<String, String> _sentences;
to:
Map<String, dynamic> _sentences;

**Comment by NTMS2017** [comment]
@mdudek, thanks its working now. Kind regards,

**Comment by NTMS2017** [comment]
@mdudek my second problem how do I call from other pages? Example in my drawer menu I have and list of drawer page link like "account". How do I call the json from drawer menu link or other pages (***.dart) file?

**Comment by NTMS2017** [comment]
Hi, In drawer_menu.dart I import "../main.dart" but still getting these error:
------------------------------------------------------------------------------

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
I/FlutterActivityDelegate(10986): onResume setting current activity to this
I/flutter (10986): Load tr
Syncing files to device Android SDK built for x86...
D/        (10986): HostConnection::get() New Host Connection established 0xa1f23800, tid 11005
D/EGL_emulation(10986): eglMakeCurrent: 0xa9d0dfe0: ver 3 0 (tinfo 0xa1f03320)
I/flutter (10986): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (10986): The following NoSuchMethodError was thrown building DrawerMenu(dirty):
I/flutter (10986): The method 'trans' was called on null.
I/flutter (10986): Receiver: null
I/flutter (10986): Tried calling: trans("drawerHeaderAccountName")
I/flutter (10986): 
I/flutter (10986): When the exception was thrown, this was the stack:
I/flutter (10986): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
I/flutter (10986): #1      DrawerMenu.build (package:capitalbank/drawer/drawer_menu.dart:29:69)
I/flutter (10986): #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3695:28)
I/flutter (10986): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
I/flutter (10986): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10986): #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (10986): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (10986): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10986): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10986): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (10986): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10986): #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (10986): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (10986): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10986): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10986): #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (10986): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10986): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10986): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (10986): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10986): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (10986): #21     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (10986): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (10986): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10986): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10986): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (10986): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10986): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10986): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (10986): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10986): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10986): #31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (10986): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10986): #33     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4759:32)
I/flutter (10986): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10986): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10986): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (10986): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10986): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10986): #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (10986): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (10986): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (10986): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10986): #43     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (10986): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (10986): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (10986): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10986): #47     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (10986): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (10986): #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2900:38)
I/flutter (10986): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10986): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (10986): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10986): #53     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (10986): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (10986): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (10986): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10986): #57     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter (10986): #58     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter (10986): #59     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (10986): #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (10986): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (10986): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (10986): #63     _invoke (dart:ui/hooks.dart:120:13)
I/flutter (10986): #64     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (10986): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by mdudek** [comment]
Just use 'DemoLocalizations.of(context).trans('resource_key')' instead of string in code.

**Comment by NTMS2017** [comment]
In main.dart I am calling like:
  CapitalLocalizations.of(context).trans('appTitle'),

And in drawer_menu.dart I am calling same as:
new UserAccountsDrawerHeader(
  accountName: new Text(CapitalLocalizations.of(context).trans('drawerHeaderAccountName')),

And still getting these error.

And here is my json:

{
  "mainTitle": "Capitalbank",
  "appTitle": "Mobile Branch",
  "drawerHeaderAccountName": "Capitalbank"
}

**Comment by NTMS2017** [comment]
Error on emulator is:
NoSuchMethodError: The method 'trans' was called on null.
Receiver: null
Tried calling: trans("drawerHeaderAccountName")

**Comment by NTMS2017** [comment]
I moved the class DemoLocalizations and the class DemoLocalizationsDelegate into another page  as demo_localizations.dart next to main.dart. In main dart I am trying to call second page. But the loaded Localization is not working. Here is my second Page code:


import 'package:flutter/material.dart';
import '../demo_localizations.dart';

class SecondPage extends StatefulWidget {
  @override
  _SecondPageState createState() => new _SecondPageState();
}

class _SecondPageState extends State<SecondPage> {
	@override
	Widget build(BuildContext context) {
		return new Scaffold(
			appBar: new AppBar(
				title: new Text('Second Page'),
			),
			body: new Center(
				// TODO: This part is not working
				  child: new Text(DemoLocalizations.of(context).trans('secondPageTitle')),

				// TODO: This is working without using DemoLocalizations
				//child:new Text('Second Page'),
			),
		);
	}
}

**Comment by anilcancakir** [comment]
I'm sorry for late. I have working on a new package. It's working well for internationalization. You can look this source. I haven't time for updating this repository. If you can do it, I have thank you for your commit.

Just look this classes, you can use with copy and paste.
https://github.com/anilcancakir/magic_package/tree/master/lib/src/lang

**Comment by NTMS2017** [comment]
@anilcancakir thanks, I will look at it...

**Comment by NTMS2017** [comment]
@anilcancakir It will good to make a small documentation about the magic_package in Flutter.io or similar. 
Kind Regards

**Comment by NTMS2017** [comment]
@anilcancakir thanks. with magic_package I modified a bit and now is working with multiple page. How can I contribute your flutter-internationalization repository? I made a small picture wiki to show how to use the lang.dart, lang_delegate.dart and the helpers.dart

**Comment by anilcancakir** [comment]
@NTMS2017 you can send a pull request for it and you can add the wiki texts in readme.md file. I can complete for this. Thanks.
